default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: cards_development
test:
  <<: *default
  database: cards_test
production:
  <<: *default
#     url: <%= ENV['DATABASE_URL'] %>
  database: cards_production
  username: cards
  password: <%= ENV['CARDS_DATABASE_PASSWORD'] %>
